apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventoory
  labels:
    app: inventoory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventoory
  template:
    metadata:
      labels:
        app: inventoory
    spec:
      containers:
        - name: inventoory
          image: username/inventoory:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
